[package]
name = 'Thundind'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
ThundindCoin = "0xCAF0"
ThundindToken = "0xCAF1"
ThundindMarket = "0xCAF2"
