[package]
name = 'LaunchPad'
version = '1.0.0'

[dependencies.AptosFramework]
git = 'https://github.com/davidiw/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
Thundind = "_"

[dev-addresses]
Thundind = "0xcaf0"
